### ISSUE TITLE
Alpine/Latest permissions Issues

### ISSUE THREAD

**Issue by narokuu** [rHomelab/Red-DiscordBot-Docker#35]
Error: Invalid value for '--data-path': Directory '/redbot/data' is not writable.

-narokuu

**Comment by tigattack** [comment]
Thanks naro.

For my future reference, this was resolved with the instructions in the readme, but the handling of all this could do with a review.

I plan to drop the Alpine-based image as it provides little value over the Debian-based image yet has a far more convoluted build process.

When I do that, I'll also review how permissions and such are handled.
